---
title: "silt mica relation"
author: "Greta Dobetsberger"
date: '2023-10-19'
output: pdf_document
---

# Silt content and mica content relation

```{r packages and data}
require("rstudioapi")
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) #to set working directory as current fil location

library(readxl) #to import data
library(tidyverse) #to manipulate data
library(dplyr)
library(ggmosaic) #to do mosaic plot
# library(vdc) #to use assocstats
library(viridis) #to use color gradient
```

## Augure's data

```{r}
# import data auger
dataAuger2022 <- read_excel("DataAuger2022.xlsx", sheet=1, na="NA")

# rename all variable to be easier to manipulate
dataAuger2022 <- dataAuger2022 %>% rename_at('% pente', ~'pente')
dataAuger2022 <- dataAuger2022 %>% rename_at('Numéro horizon', ~'horizon')
dataAuger2022 <- dataAuger2022 %>% rename_at('profondeur limite inférieure (cm)2', ~'depth_inf')
dataAuger2022 <- dataAuger2022 %>% rename_at('profondeur limite supérieure (cm)', ~'depth_sup')
dataAuger2022 <- dataAuger2022 %>% rename_at('Epaisseur (cm)', ~'epaisseur')
dataAuger2022 <- dataAuger2022 %>% rename_at('Texture corrigée 2023', ~'Texture_2023')  #idk why it doesn't work here
dataAuger2022 <- dataAuger2022 %>% rename_at('EG %', ~'stone_elements')
dataAuger2022 <- dataAuger2022 %>% rename_at('Réserve eau utile (mm) NEW...35', ~'water_reservoir')

# create a new column for topography that only contains the number of the topography 
dataAuger2022$topo <- as.numeric(gsub("[^0-9]+", "", dataAuger2022$topographie))

# filter out all data that isn't on the slope (drainage type DLS) and make smaller usable dataframe
Auger_NA <- dataAuger2022 %>% 
  filter(topo %in% c("5", "4", "3")) %>%
  select(c("sondage_N", "Texture_2023", "depth_sup", "arbre_plus_proche", "topo", "mica"))

Auger <- Auger_NA %>% na.omit # take out NA variables

#create new column with textures divided in three classes based upon their presence of silt
Auger$Silt_class <- ifelse(
  Auger$Texture_2023 %in% c("A", "Alo", "AS"), 
  "low", 
  ifelse(
    Auger$Texture_2023 %in% c("SL", "SA", "S"), 
    "intermediate", 
    "high"))

# set mica and silt_class as factor 
Auger$mica=as.factor(Auger$mica)
Auger$Silt_class=as.factor(Auger$Silt_class)
```


```{r}
# Perform the chi-squared test (don't take ordinal )
chi_sq_test <- chisq.test(Auger$mica, Auger$Silt_class)
print(chi_sq_test)

# Create a contingency table
contingency_table <- table(Auger$mica, Auger$Silt_class)
print(contingency_table)

# Obtain Cramér's V and other statistics
# assoc_stats <- assocstats(contingency_table)
# print(assoc_stats)
```

```{r}
#reverte silt class for ease of reading plot
Auger$Silt_class_revert <- factor(Auger$Silt_class, 
                                  levels = rev(levels(Auger$Silt_class)))

colSilt <- viridis(3) #color for silt content classes

#mosaic plot of silt class with mica
ggplot(data=Auger) +
   geom_mosaic(aes(x = product(Silt_class_revert, mica), 
                   fill = Silt_class_revert))+
   labs(title = "Mica Silt relation") +
   scale_fill_manual(name = "silt content", values = setNames(colSilt, levels(Auger$Silt_class_revert)))+
   theme_minimal()
```


